# Generated by Django 4.2.13 on 2024-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_kiosk_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
