# Generated by Django 4.2.13 on 2024-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0011_alter_adam_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("report", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
